$(document).ready(function(){
	$('.pill_signup_li').click(function(){
		$('.hr_1').hide();
	});
	$('.pill_signup_li').click(function(){
		$('.hr_2').show();
	})
	$('.pill_login_li').click(function(){
		$('.hr_2').hide();
	});
	$('.pill_login_li').click(function(){
		$('.hr_1').show();
	})
})